# Default .nextaudit.toml
# This file is committed as a reasonable default for the prototype.

[project]
# router can be "app", "pages", or "mixed"
router = "app"
# target can be "node" or "edge"
target = "node"

[thresholds]
# threshold for large files (KB)
large_file_kb = 200

# Top-level ignore list (matches Config.ignore: Option<Vec<String>>)
ignore = [".git", "node_modules", "target"]
