# Example .nextaudit.toml

[project]
# router = "app" # or "pages" or "mixed"
# target = "node" # or "edge"

[thresholds]
# threshold for large files (KB)
large_file_kb = 200

[ignore]
# list of directory names to ignore during scan
# e.g.
# directories = [".git", "node_modules", "target"]
directories = [".git", "node_modules", "target"]
